### ISSUE TITLE
Categories and Facets not rendering as different colours

### ISSUE THREAD

**Issue by whiteleyrod** [Microsoft/timelinestoryteller#122]
I seem to be able to add categories and facets just fine to a dataset I have, but each instance represented on a timeline shows up as the same colour. I can change the colour through the picker, which then changes all instances (irrespective of category or facet) in the timeline. The Legend changes colours, just nothing else. 

![image](https://user-images.githubusercontent.com/32126821/30636456-2de33b06-9dfe-11e7-8cdf-609ce39082f1.png)
The difference categories are being recognised as you can see here if I select:
![image](https://user-images.githubusercontent.com/32126821/30636513-590761f4-9dfe-11e7-8e2f-e0cfb39f2d41.png)
Any time I change a colour for a category, everything changes to the most recently selected colour:
![image](https://user-images.githubusercontent.com/32126821/30636540-77b625c2-9dfe-11e7-8c14-cefed354eb6b.png)

Windows machine using PowerBI Desktop Version: 2.50.4859.502 64-bit (September 2017)

Session Diagnostics:
Feedback Type:
Frown (Error)

Timestamp:
2017-09-20T09:24:15.0179421Z

Local Time:
2017-09-20T12:24:15.0179421+03:00

Product Version:
2.50.4859.502 (PBIDesktop) (x64)

Release:
September 2017

IE Version:
11.0.9600.18639

OS Version:
Microsoft Windows NT 6.3.9600.0 (x64 en-US)

CLR Version:
4.6.2. or later [Release Number = 460805]

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Peak Working Set:
517 MB

Private Memory:
356 MB

Peak Virtual Memory:
33.8 GB

User ID:
659df0e0-b940-48c1-a8a1-d4d587cac321

Session ID:
7384866d-7959-44ae-be58-b127a33da434

Telemetry Enabled:
True

Model Default Mode:
Import

Snapshot Trace Logs:
C:\Users\rwhiteley\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot146091763.zip

Performance Trace Logs:
C:\Users\rwhiteley\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_EnableReportTheme
PBI_numericSlicerEnabled
PBI_daxTemplatesEnabled

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
CustomConnectors

Disabled DirectQuery Options:
PBI_DirectQuery_Unrestricted

Cloud:
GlobalCloud

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared IMTendon = let
    Source = Excel.Workbook(File.Contents("D:\ODF\Papers\In Progress\Hamstring Running Arnlaug\Intramuscular tendon involvement analysis.xlsx"), null, true),
    Table2_Table = Source{[Item="Table2",Kind="Table"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Table2_Table,{{"MRN", type text}, {"GFID", type text}, {"Date", type date}, {"IMTD", type text}, {"IMTD deg", type text}, {"Waviness", type text}, {"Time to RTP", Int64.Type}, {"Date Discharge", type date}})
in
    #"Changed Type";

**Comment by stopyoukid** [comment]
Could you provide a test dataset that we can use that exhibits this problem?

**Comment by whiteleyrod** [comment]
Here's the excel sheet is based on, is this enough?

**Comment by stopyoukid** [comment]
I do not see any file.  You may have to go to this issue on GitHub, and attach the file manually on a comment.

**Comment by whiteleyrod** [comment]
Ok, I attached the excel file in the previous email but I'll go to github
when I get home & upload there.
Attached here again in case... (intramuscular tendon analysis)

**Comment by whiteleyrod** [comment]
Here's a link to the onedrive excel file:
https://1drv.ms/x/s!AgytcDfT4DRFhL8GmovjaclAGEsLZQ

**Comment by stopyoukid** [comment]
Thanks! I'm not seeing the issue, it seems to work on my end.  
![image](https://user-images.githubusercontent.com/2513737/30823780-2eea3602-a1e2-11e7-83f0-f1e23a7b8c32.png)

Is my setup the same? Here was my process:

1. Add timeline storyteller
2. Add the facet field
3. Add the start date field
4. Add the category field
5. Change colors on the legend

  Is this your same process?

**Comment by whiteleyrod** [comment]
Started from scratch and works here too.
All I can think of is that with the original report, I was chopping and changing facets and categories a lot, and perhaps this somehow corrupted things, ie I would put Waviness in as a Facet and IMTD degree as a category, then later remove and swap these, leave out the category, and explore the visualisation. After a couple of iterations, the colour differentiation seemed to break.
Restarting the analysis/visualisation seems to have resolved this, so good to know for next time I stuff things up.
Thanks for taking a look at this, and if I can exactly replicate the workflow for the error I'll repost, otherwise consider this resolved.

**Comment by stopyoukid** [comment]
No problem, and please do reopen if you find the steps.
