### ISSUE TITLE
Need to be able to select custom colours

### ISSUE THREAD

**Issue by bebetech** [Microsoft/timelinestoryteller#128]
Need to have some control over the colours otherwise you end up in situations like:
<img width="124" alt="colours" src="https://user-images.githubusercontent.com/1019353/31124183-a0ab535c-a886-11e7-9864-339ca792567a.PNG">

On time shouldn't be red as red to most people think late.

**Comment by mattbrehmer** [comment]
This feature exists. If you click on any colored rectangle in the legend you can re-assign the color associated with the event category. We hope to [improve the visibility of this feature](https://github.com/Microsoft/timelinestoryteller/issues/45) (Issue #45) and [possibly integrate the Power BI color picker directly](https://github.com/Microsoft/timelinestoryteller/issues/90) (Issue #90).
