### ISSUE TITLE
Annotations that have too much text, overflow the annotation container

### ISSUE THREAD

**Issue by stopyoukid** [Microsoft/timelinestoryteller#52]
![image](https://cloud.githubusercontent.com/assets/2513737/26739338/49cce2c8-4786-11e7-926f-9ee7bdce9702.png)

**Comment by mattbrehmer** [comment]
Add ellipses ('...') in cases where annotation contains very long word? I wonder how typical this case would come up.

**Comment by katua** [comment]
I bumped into this issue a couple of times while I was preparing demo. 11-12 characters is enough to overflow.
