### ISSUE TITLE
Clear a data point selection with "Clear" button

### ISSUE THREAD

**Issue by katua** [Microsoft/timelinestoryteller#82]
"Clear" button should clear a data point selection along with annotation.

![selections after clear](https://user-images.githubusercontent.com/7892199/27361613-69518512-55dd-11e7-80d3-547d9ee3ae9a.png)

**Comment by mattbrehmer** [comment]
'Clear; button is inconsistent and broken: sometimes only clearing captions and annotations but not images or selected events.
