### ISSUE TITLE
Mixed up annotations

### ISSUE THREAD

**Issue by katua** [Microsoft/timelinestoryteller#86]
Annotations get mixed up when you take one of the previously saved scene, change an annotation there and save as a new scene.
Repro steps:
1. Create a story with several scenes that include annotations.
2. Go to one of the scenes that is not the last one.
3. Add a new annotation.
4. Delete the old one.
5. Click on any other scene.
6. Come back to the scene you've created.

Expected result: Annotations are  displayed properly.
Actual result: The new annotation is in the default position, an old annotation or an annotation from a totally different scene is present.

Workaround: kill a scene and recreate it with new annotations.

Example: 
1. A scene how I saved it:
![mix ann 1](https://user-images.githubusercontent.com/7892199/27447816-583786a4-5737-11e7-94a2-99d9ecdef1ac.png)

2. The scene how it looks like after a switch between scenes and come back:
![mix ann 2](https://user-images.githubusercontent.com/7892199/27447845-70366982-5737-11e7-91ac-378fa361bb03.png)

3. The scene where the floating annotation is taken from:
![mix ann 3](https://user-images.githubusercontent.com/7892199/27447868-83933c8a-5737-11e7-86f1-558280f3950a.png)

**Comment by mattbrehmer** [comment]
Not specific to Power BI version

**Comment by mattbrehmer** [comment]
Related to #57 re: moving annotations causing them to move on other pages
