### ISSUE TITLE
Where did the horizontal scrollbar go?

### ISSUE THREAD

**Issue by katua** [Microsoft/timelinestoryteller#95]
Collapsed view doesn't fir the page and go beyond the right border. No scroll is added.
![screenshot 23](https://user-images.githubusercontent.com/7892199/27654429-06b2c586-5bf7-11e7-8f81-c4736119cc6c.png)

**Comment by mattbrehmer** [comment]
This bug was introduced recently, because on [the web version of timelinestoryteller.com](https://timelinestoryteller.com/app/), a horizontal scrollbar appears.

**Comment by mattbrehmer** [comment]
![image](https://user-images.githubusercontent.com/1696818/27709493-2680239c-5cd1-11e7-9ec1-58443c1e31ea.png)
This issue affects any combination of representation / scale / layout, not just sequential + collapsed scales with a linear representation.
